mixer/arcade-machine

demo/src/bundles/demo/demo.module.ts, src/focus.service.ts, src/input.service.ts
Previously arcade-machine would try to capture backspaces, arrow keys, and enter keys on all form elements, making it quite frustrating. I've added logic that prevents that, see demo: https://peet.io/i/16-11-c1zu8u9ga2xo0jgvka5o9v7385ej12.mp4
Note that this _only_ affects keyboard input on PC.
=> Don't try to arcade-machine-ify inputs that would have an effect in html forms

package.json, src/input.service.ts, tsconfig.json
Disable navigation when input pane is visible. This will make arcade machine specific to UWP though, which I guess is fine?
=> Disable nav on inputpane

src/focus.service.ts
FocusService now regards root as a the element to operate in when it comes to scrolling.
Also fixed a bug where if multiple animates are triggered during scrolling, only the last one will be activated because top is updated before the animation is actually carried out
=> scrolling now aware of safety padding container

readme.md, src/arc.directive.ts, src/event.ts, src/focus.service.ts, src/model.ts, src/registry.service.ts
In the UI, I needed to bind events to the focus incoming event, without needing to use the directive and instead hooking via the service manually. (A service can optionally be injected, a missing directive will break the build if the directive doesn't exist.) This:
- renames some stuff and makes it easier to attach custom handlers for elements
- adds a `arc-exclude-this` to make an element unfocusable ( cc @Antariano ). Note that this does not exclude element children.
- moves the lifecycle hooks to onIncoming and onOutgoing which are called on the next element and previous element, respectively.
- flattens down some selection logic; tabIndex is defined to exist on _any_ focusable elements, not just those who explicitly have an index defined. E.g. `<a>asdf</a>` will have a tabIndex of …
=> Distinguish incoming and outgoing focuses, allow support for custom event attaches

readme.md, src/arc.directive.ts
Splitting the `arc-capture` directive into `arc-capture-outgoing` and `arc-capture-incoming`
=> directive for capturing incoming events

src/focus.service.ts
Fixed divs being unselectable even with arc by not allowing tabIndex to default to -1 unless explicitly set.
=> fixed divs being unselectable

src/input.service.ts
Chrome used to throw an exception here when it can't read selectionStart and selectionEnd
=> makes checkbox not throw exceptions

src/input.service.ts
so that the consumer of arcade-machine can control the inputPane. I didn't see the point of wrapping the inputPane under one more layer of interface (e.g. `public showInputPane`)
=> making inputPane public

src/focus.service.ts
This fixes a bug where input elements are still selected even when the arcade-machine has moved away
=> blurring element when deselecting

src/focus.service.ts, src/input.service.ts
This is to deal with fullscreen, when the elements become outside of the xbox wrapper. In that case we want to manually set the root element to document.body (or some other wrapper).
=> exposing setRoot

src/focus.service.ts
Arcade machine throws exceptions of two focus elements do not share root element.
The look up keeps traversing up till HTML element until it returns null.
BuiDialog DOM element is appended directly to body therefore does not share the app root `<b-app>` therefore preventing the creation of bui-dialog
=> prevent errors if common ancestor is above root

src/focus.service.ts
Doing away with arc-selected in preference of just using direct.  Arc--selected updates all the way up the dom applying classes, which is not needed.
=> Class cleanup

demo/src/bundles/demo/benchmark-page.component.ts, demo/src/bundles/demo/page1.component.ts, src/arc.directive.ts, src/focus.service.ts, src/model.ts, src/registry.service.ts
I forced tabIndex to be set for elements that have the `arc` directive applied. Now that we use tabIndex checks for all things, the explicit focusable role checks can be removed (browsers will automatically set tabIndexes on other focusable elements).  Also, tabIndex is a 'native' property that can be accessed without getAttribute. This also lets us remove the "only tab index" flag and get rid of the class application, since we know the `:focus` selector will always work.
I also dropped the "enable exclusion" flag in favor a feature-detection mechanism. If there are excluded in the elements in the registry, we'll check for them, otherwise we skip it. This makes configuration a little less finicky.
I noticed the isVisible check was taking a good bit of time, so I modified it so that that …
=> Improve arcade-machine focus performance 3-4.5x

src/focus.service.ts
In focus by raycast; skip elements that are not under focus root. Otherwise focus may move out of focus trap
=> raycast - skip elements not under focus trap

src/focus.service.ts
This is required to differentiate between element being focused using keyboard (arcade-machine) vs using mouse/touch.
=> added focus classes

src/focus.service.ts, src/input.service.ts
selectNode gets called twice because of the focus method inside selectNode triggers focusin
=> prevent duplicate calls to selectNode

src/focus.service.ts
if Element has no tabindex defined, `el.tabindex` returns `null` in chrome whereas it returns `0` in Edge leading to focusByRaycast returning un-focusable elements.
=> Use getAttribute instead of tabindex for consistent browser behavior

src/focus.service.ts
Added events around SelectNode that can be intercepted to modify focus behavior.
- `arcfocuschanging` can be intercepted to complete smooth scroll before triggering native focus. This will prevent browser from rescrolling the page to bring element in view.
- `arcselectingnode` can be intercepted to redirect focus to another element
=> DOM events to intercept arcade machine focus

readme.md, src/arc.directive.ts, src/focus-strategies/focus-by-registry.ts, src/focus.service.ts, src/model.ts
- Added FocusByRegistry to be able to manually define the next focus element.
- Also Fixed a bug that broke arcade-machine if no last focused element is present
=> Added focus by registry

src/focus.service.ts
This fixed arcade machine skipping adjacent elements because of the rounding error.
=> fixed arc skipping adjacent elems

demo/src/bundles/demo/page1.component.ts, readme.md, src/arc.directive.ts
- Added *ngFor support for arc-default-focus
- Fixed bug in Edge not adding tabindex="0" to elements with arc directive
=> Add *ngFor support for arc-default-focus

package-lock.json, package.json
@saadataz tests here are not functional at all, (the warnings from the node v8 typings are irrelevant).
Maybe we should use the testing setup used in frontend2, at least that works. @UnwrittenFun @RobertGoins if you have any time that'd be great!
=> chore(npm): use node v8 and npm 5

demo/src/bundles/demo/page1.component.ts, readme.md, src/arc.directive.ts, src/focus.service.ts, src/model.ts
This is useful when you want to automatically transfer focus from a bigger container to its child elements. 
- Transferring focus from a video container to its controls.
=> Introducing Arc-Focus-Inside

demo/src/bundles/demo/page1.component.ts, src/focus.service.ts
The fix to ignore elements with `arc-focus-inside` that are empty
=> fix(focus inside): unreverted focus inside fixes

package-lock.json, package.json
When publish tag 2.0.3, publishing to master failed. I need to merge the tag commit to master.
=> Merge tag 2.0.3 to master
