mixer/arcade-machine

- demo/src/bundles/demo/demo.module.ts
- src/focus.service.ts
- src/input.service.ts
This is a pretty gnarly POC but seems to work alright. Demo: https://peet.io/i/16-12-17alcz50db754wrxscw37taf9t3o11.mp4
> Implement automatic scrolling

- src/input.service.ts
- src/model.ts
and "better" formatting because I used visual studio code to auto format some files
> arcade-machine now detects bumpers, triggers, x and y

- src/input.service.ts
Makes controller polling work on edge/xbox
> Edge polling

- .gitignore
- src/input.service.ts
fixes for desktop browser, adding in a default focus element for triggers
> fixes, trigger support

- src/input.service.ts
This fixes the issue where the pointer reappears after minimizing on xbox
> corrected gamepadIputEmulation being allowed to default to mouse

- src/input.service.ts
keyboardVisible wasn't updating properly
> fixed keyboardVisible not updating

- readme.md
- src/arc.directive.ts
- src/focus.service.ts
Sorry I meant tabIndex. With the tabIndex as it is now edge will select the surrounding div rather than the elements themselves.
> fixed tab index issue

- src/focus.service.ts
> Remove opacity check

- src/focus.service.ts
- src/input.service.ts
It used to scroll only upon directional changes, now it scrolls when focus is manually set as well
> arcade-machine now scrolls whenever an element is focused

- src/event.ts
- src/focus.service.ts
- src/input.service.ts
And changing emitted object to IArcEvents
> adding back and submit event emitters

- src/input.service.ts
and putting global emitters below local emitters (ones attached to elements)
> adding directional event emitters

- src/focus.service.ts
This seems to behave a little bit better
> changing history.back to location.back

- src/input.service.ts
- src/model.ts
Adding event emitters for menu and view buttons.
Also some slight code cleanup.
> View & Menu buttons

- readme.md
- src/arc.directive.ts
- src/focus.service.ts
- src/model.ts
Including an arc-exclude input that exclude the element and all its children
> exclude-this and exclude

- src/focus.service.ts
- src/input.service.ts
Switching gamepadinputemulation to keyboard
> Switch to Keyboard Nav

- package.json
- src/focus.service.ts
- src/input.service.spec.ts
Arcade machine can afford to be a little inspecific about angular versions here, ultimately if needed we can lock versions in frontend
> Allow angular v4

- src/focus.service.ts
Added a flag to enable and disable ray trace focus finder.
This is needed before we tailor the clients to be able to use this feature.
> added flag for enable RayTrace finder

- demo/src/bundles/demo/benchmark-page.component.ts
- demo/src/bundles/demo/demo.module.ts
- demo/src/bundles/demo/page1.component.ts
- demo/src/bundles/demo/page2.component.ts
- demo/src/bundles/demo/smooth-scroll.component.ts
- src/event.ts
- src/focus.service.ts
- src/input.service.ts
- src/model.ts
- src/registry.service.ts
- tsconfig.json
- This will help us fall into avoidable traps in the future
> Enable strict null checking

- src/focus.service.ts
> fix: Prevent selectNode outside the focus trap

- src/input.service.ts
So that the project can build.
> fix: fix null check errors
